// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7S_9b-0dwzXsV_qQK2Lz9Ah6C_6J0UIU',
    appId: '1:719392599071:web:93d76b74ebf7237799792a',
    messagingSenderId: '719392599071',
    projectId: 'flutter-firebase-notific-22a9d',
    authDomain: 'flutter-firebase-notific-22a9d.firebaseapp.com',
    storageBucket: 'flutter-firebase-notific-22a9d.appspot.com',
    measurementId: 'G-3ME360276G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wXSDFxV07Z8M9nIbbJZWwERBSK1Trl0',
    appId: '1:719392599071:android:6aeed733742c338499792a',
    messagingSenderId: '719392599071',
    projectId: 'flutter-firebase-notific-22a9d',
    storageBucket: 'flutter-firebase-notific-22a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWKUK1JZLdB8MGOxh9_H9qAlDItOX8eA',
    appId: '1:719392599071:ios:98c29b91ec6adf6099792a',
    messagingSenderId: '719392599071',
    projectId: 'flutter-firebase-notific-22a9d',
    storageBucket: 'flutter-firebase-notific-22a9d.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGWKUK1JZLdB8MGOxh9_H9qAlDItOX8eA',
    appId: '1:719392599071:ios:98c29b91ec6adf6099792a',
    messagingSenderId: '719392599071',
    projectId: 'flutter-firebase-notific-22a9d',
    storageBucket: 'flutter-firebase-notific-22a9d.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );
}
